### ISSUE TITLE
Font Awesome 6 にすれば 5 のアイコンのままでも表示するなら 5 の設定・ファイル一式無くてよくない？

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/font-awesome-versions#5]
6のファイルで 5で使ってたユーザーが問題なく表示されるなら、
ユーザーが 5から6に切り替え作業しなくても、5のユーザーは勝手に6に切り替えで良いのではないか？
そうすれば 5 のファイルも完全抹殺できるので容量も節約できる。

- [ ] まずは Font Awesome の公式サイトで 5 のクラス名のアイコン使ってた場合でもそのままでほんとに良さげか確認
- [x] とりあえず 5 のファイルは一応まだ残しつつ、バージョン切り替えの選択から Font Awesome 5 の設定は削除
- [x] 5 を使う設定になってるユーザーは 6 を使うように自動設定

※ 4系はLightningのG2モードで使っている場合があるのでまだ残す

**Comment by drill-lancer** [comment]
@kurudrive 
これは 5 を残すという結論が出たような気がしますが・・・
